### ISSUE TITLE
'Equation' object has no attribute 'getParticipatingVariables'

### ISSUE THREAD

**Issue by shubhamugare** [WhiRLVerification/WhiRL#1]
I followed all the installation steps in the README. Getting this error message while running the verifier. 

Command:
`python3 queries/marabou_property_1.py model/output_graph.pb 5`

Output:
```
Traceback (most recent call last):
  File "queries/marabou_property_1.py", line 128, in <module>
    main()
  File "queries/marabou_property_1.py", line 125, in main
    k_test(filename,k,False)
  File "queries/marabou_property_1.py", line 22, in k_test
    network, input_op_names, output_op_name = create_network(filename,k)
  File "queries/marabou_property_1.py", line 12, in create_network
    network = Marabou.read_tf_k_steps(filename, k,inputName=input_op_names,outputName=output_op_name)
  File "/home/sugare2/UIUC/Marabou/maraboupy/Marabou.py", line 55, in read_tf_k_steps
    return MarabouNetwork_K_StepsTF(filename, K, inputName, outputName, savedModel, savedModelTags)
  File "/home/sugare2/UIUC/Marabou/maraboupy/MarabouNetwork_K_StepsTF.py", line 48, in __init__
    self.processBiasAddRelations()
  File "/home/sugare2/UIUC/Marabou/maraboupy/MarabouNetwork_K_StepsTF.py", line 423, in processBiasAddRelations
    participating = equ.getParticipatingVariables()
AttributeError: 'Equation' object has no attribute 'getParticipatingVariables'
```

**Comment by chenxi-yang** [comment]
Hi,

I met the same issue, did you find a solution for it? Thank you very much!

Bests,
Chenxi

**Comment by shubhamugare** [comment]
Hi,

The authors sent me this code https://zenodo.org/record/4769612#.Yh_QthPMK3I that had some missing files needed to make it work.

**Comment by chenxi-yang** [comment]
Thank you!
